export const USERS_LIST_REQUEST = 'USERS_LIST_REQUEST';
export const USERS_LIST_FETCHING = 'USERS_LIST_FETCHING';
export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS';
export const USERS_LIST_FAILURE = 'USERS_LIST_FAILURE';